[package]
name = "tsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
indicatif = "0.17.8"
serde = { version = "1.0.188", features = ["derive"] }

[dev-dependencies]
clap = { version = "4.5.19", features = ["derive"] }
clap_complete = "4.5.32"
