[package]
name = "tsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.3"
chrono = { version = "0.4.30", features = ["serde"] }
clap = { version = "4.4.1", features = ["derive", "unstable-styles"] }
colored = "2.0.4"
indicatif = "0.17.6"
serde = { version = "1.0.188", features = ["derive"] }
symphonia = { version = "0.5.3", features = ["all-codecs", "all-formats"] }
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
clap = { version = "4.4.1", features = ["derive"] }
clap_complete = "4.4.0"
