[package]
name = "tsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
colored = "2.0.4"
indicatif = "0.17.6"

[dev-dependencies]
clap = { version = "4.4.1", features = ["derive"] }
clap_complete = "4.4.0"
