name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Upload
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build (release)
        run: |
          mkdir release
          cargo build --locked --release
          cp ./target/release/tsync release

      - name: Generate shell completions
        run: |
          mkdir release/completions
          release/tsync completion bash > release/completions/tsync.bash
          release/tsync completion zsh  > release/completions/_tsync
          release/tsync completion fish > release/completions/tsync.fish
          release/tsync completion powershell > release/completions/tsync.ps1

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tsync-${{ matrix.os }}-${{ github.ref_name }}-release
          path: release/**/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            release/tsync
            release/completions/tsync.bash
            release/completions/_tsync
            release/completions/tsync.fish
            release/completions/tsync.ps1