name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build (release)
        run: |
          mkdir release
          cargo build --locked --release
        
      - name: Copy binary (Unix)
        if: runner.os != 'Windows'
        run: cp ./target/release/tsync release/
        
      - name: Copy binary (Windows)
        if: runner.os == 'Windows'
        run: Copy-Item ./target/release/tsync.exe release/

      - name: Generate shell completions
        run: |
          mkdir release/completions
          release/tsync completion bash > release/completions/tsync.bash
          release/tsync completion zsh  > release/completions/_tsync
          release/tsync completion fish > release/completions/tsync.fish
          release/tsync completion powershell > release/completions/tsync.ps1

      - name: Create tarball of release files
        run: tar -czvf tsync-${{ matrix.os }}-${{ github.ref_name }}-release.tar.gz -C release .

      - name: Upload release tarball
        uses: actions/upload-artifact@v4
        with:
          name: tsync-${{ matrix.os }}-${{ github.ref_name }}-release
          path: tsync-${{ matrix.os }}-${{ github.ref_name }}-release.tar.gz

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            artifacts/**/*